# Server
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## H2 Database (In-Memory - no installation needed)
#spring.datasource.url=jdbc:h2:mem:cruddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=


# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## H2 Console (access at http://localhost:8080/h2-console)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console



# App Name
spring.application.name=crud-app
